Repository xprobe-inc/mars, pull requests merged in 2022-08, with the labels that each got.

#3 Fix some CI issues
  .github/workflows/docker-cd.yml
  azure-pipelines.yml
Labels: type: enhancement

#12 CI: Fix benchmark CI
  .github/workflows/benchmark-ci.yml
  azure-pipelines.yml
  benchmarks/asv_bench/asv.conf.json
Labels: mod: CI

#9 Lib: fsspec integration
  mars/dataframe/datastore/to_parquet.py
  mars/lib/filesystem/__init__.py
  mars/lib/filesystem/_glob.py
  mars/lib/filesystem/azure.py
  mars/lib/filesystem/base.py
  mars/lib/filesystem/core.py
  mars/lib/filesystem/fsspec_adapter.py
  mars/lib/filesystem/tests/test_filesystem.py
  mars/lib/filesystem/tests/test_fsspec_adapter.py
  setup.cfg
Labels: mod: lib, type: feature
