Repository xprobe-inc/mars, pull requests merged in 2022-12, with the labels that each got.

#87 fix: Modify signature of `df.map_chunk`
  mars/dataframe/base/map_chunk.py
  mars/dataframe/base/tests/test_base_execution.py
Labels: type: bug, mod: dataframe

#89 Support df_or_series output type for remote functions
  mars/remote/core.py
  mars/remote/tests/test_remote_function.py
Labels: type: enhancement, mod: dataframe

#95 Fix some CI issues
  .github/workflows/platform-ci.yml
  azure-pipelines.yml
Labels: type: bug, mod: CI

#111 Fix: map_chunk output type inference
  mars/dataframe/base/map_chunk.py
  mars/dataframe/base/tests/test_base_execution.py
Labels: type: bug
